'use client'

import { useEffect, useState } from 'react'
import Image from 'next/image'
import { createClient } from '@/lib/supabase/client'
import { ArrowUpRight, CalendarDays, Check, ChevronDown, Clock3, HeartPulse, Menu, Phone, ShieldCheck, Sparkles, Stethoscope, X } from 'lucide-react'

type Service = { id: string; name: string; detail: string; status: 'Aktif' | 'Draft'; color: string; sort_order: number }

const serviceIcons = [Stethoscope, HeartPulse, ShieldCheck, Sparkles, HeartPulse, CalendarDays, Stethoscope, Phone]
const serviceColors = ['bg-[#d8efe5]', 'bg-[#f8dfd3]', 'bg-[#e1e8f6]', 'bg-[#f7edc9]', 'bg-[#e7def7]']

const faqs = ['Apakah bisa konsultasi secara online?', 'Bagaimana cara membuat janji temu?', 'Apakah menerima asuransi kesehatan?']

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [openFaq, setOpenFaq] = useState<number | null>(null)
  const [booked, setBooked] = useState(false)
  const [services, setServices] = useState<Service[]>([])
  const [servicesLoading, setServicesLoading] = useState(true)

  useEffect(() => {
    const supabase = createClient()
    const loadServices = async () => {
      const { data } = await supabase
        .from('services')
        .select('id,name,detail,status,color,sort_order')
        .eq('status', 'Aktif')
        .order('sort_order')
      setServices((data ?? []) as Service[])
      setServicesLoading(false)
    }
    void loadServices()
  }, [])

  return (
    <main className="min-h-screen overflow-hidden bg-background text-foreground">
      <div className="bg-primary px-5 py-2 text-center text-[11px] font-medium tracking-[0.18em] text-primary-foreground">KLINIK BUKA SETIAP HARI · 07.00—21.00 WIB</div>
      <nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-6 lg:px-10">
        <a href="#top" className="flex items-center gap-3 font-semibold tracking-tight"><span className="grid size-9 place-items-center rounded-full bg-accent text-accent-foreground"><HeartPulse className="size-5" /></span><span className="text-xl">ruang<span className="text-secondary">sehat</span></span></a>
        <div className="hidden items-center gap-8 text-sm text-muted-foreground md:flex"><a href="#layanan" className="transition-colors hover:text-foreground">Layanan</a><a href="#cerita" className="transition-colors hover:text-foreground">Cerita kami</a><a href="#faq" className="transition-colors hover:text-foreground">FAQ</a></div>
        <a href="#janji" className="hidden items-center gap-2 rounded-full bg-secondary px-5 py-3 text-sm font-semibold text-secondary-foreground transition-transform hover:-translate-y-0.5 md:flex">Buat janji <ArrowUpRight className="size-4" /></a>
        <button className="rounded-full border border-border p-2 md:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label="Buka menu">{menuOpen ? <X className="size-5" /> : <Menu className="size-5" />}</button>
      </nav>
      {menuOpen && <div className="mx-5 flex flex-col gap-4 rounded-2xl border border-border bg-card p-5 text-sm md:hidden"><a href="#layanan" onClick={() => setMenuOpen(false)}>Layanan</a><a href="#cerita" onClick={() => setMenuOpen(false)}>Cerita kami</a><a href="#faq" onClick={() => setMenuOpen(false)}>FAQ</a><a href="#janji" onClick={() => setMenuOpen(false)} className="font-semibold text-secondary">Buat janji →</a></div>}

      <section id="top" className="mx-auto grid max-w-7xl gap-12 px-5 pb-20 pt-8 lg:grid-cols-[0.9fr_1.1fr] lg:items-center lg:px-10 lg:pb-28 lg:pt-16">
        <div className="max-w-xl"><p className="mb-6 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.2em] text-accent"><span className="size-2 rounded-full bg-accent" /> Kesehatan, dengan cara yang manusiawi</p><h1 className="font-serif text-5xl leading-[0.98] tracking-[-0.04em] text-primary sm:text-6xl lg:text-8xl">Rawat tubuh.<br /><em className="font-normal text-secondary">Tenangkan pikiran.</em></h1><p className="mt-8 max-w-md text-base leading-7 text-muted-foreground">Klinik modern untuk Anda yang ingin merasa lebih baik — bukan sekadar terlihat baik. Kami hadir dengan waktu, perhatian, dan perawatan yang utuh.</p><div className="mt-9 flex flex-wrap items-center gap-4"><a href="#janji" className="rounded-full bg-primary px-6 py-3.5 text-sm font-semibold text-primary-foreground shadow-lg shadow-primary/15 transition-transform hover:-translate-y-1">Mulai perjalanan sehat <ArrowUpRight className="ml-2 inline size-4" /></a><a href="#layanan" className="text-sm font-semibold text-primary underline decoration-secondary decoration-2 underline-offset-8">Lihat layanan</a></div><div className="mt-12 flex items-center gap-4"><div className="flex -space-x-2"><div className="grid size-9 place-items-center rounded-full border-2 border-background bg-[#d4a58e] text-xs font-semibold">DA</div><div className="grid size-9 place-items-center rounded-full border-2 border-background bg-[#8fb8a8] text-xs font-semibold">NS</div><div className="grid size-9 place-items-center rounded-full border-2 border-background bg-[#e1c27d] text-xs font-semibold">IP</div></div><p className="text-xs leading-5 text-muted-foreground"><span className="font-semibold text-foreground">4.9/5 dari 2.000+</span><br />pasien yang merasa terbantu</p></div></div>
        <div className="relative"><div className="absolute -right-16 -top-16 size-48 rounded-full bg-accent/15 blur-2xl" /><div className="relative overflow-hidden rounded-[2rem] rounded-br-[8rem] bg-muted"><Image src="/clinic-hero.png" alt="Dokter sedang berbincang dengan pasien di ruang klinik" width={1200} height={750} className="h-auto w-full object-cover" priority /></div><div className="absolute -bottom-6 left-5 flex max-w-[230px] items-center gap-3 rounded-2xl bg-card p-4 shadow-xl shadow-primary/10"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-accent/15 text-accent"><ShieldCheck className="size-5" /></span><p className="text-xs font-medium leading-5">Dokter terpercaya.<br /><span className="text-muted-foreground">Perawatan menyeluruh.</span></p></div><div className="absolute -right-3 top-8 hidden rounded-full bg-secondary px-4 py-2 text-xs font-semibold text-secondary-foreground sm:block">care that stays</div></div>
      </section>

      <section className="border-y border-border bg-card"><div className="mx-auto grid max-w-7xl grid-cols-2 divide-x divide-border lg:grid-cols-4"><div className="p-6 lg:p-9"><p className="font-serif text-4xl text-primary">12+</p><p className="mt-1 text-xs text-muted-foreground">tahun merawat Indonesia</p></div><div className="p-6 lg:p-9"><p className="font-serif text-4xl text-primary">18</p><p className="mt-1 text-xs text-muted-foreground">dokter dan terapis</p></div><div className="p-6 lg:p-9"><p className="font-serif text-4xl text-primary">4.9</p><p className="mt-1 text-xs text-muted-foreground">rating pengalaman pasien</p></div><div className="p-6 lg:p-9"><p className="font-serif text-4xl text-primary">30m</p><p className="mt-1 text-xs text-muted-foreground">rata-rata waktu tunggu</p></div></div></section>

      <section id="layanan" className="mx-auto max-w-7xl px-5 py-24 lg:px-10 lg:py-32"><div className="mb-14 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="mb-4 text-xs font-semibold uppercase tracking-[0.2em] text-accent">Yang kami lakukan</p><h2 className="max-w-lg font-serif text-4xl leading-tight text-primary sm:text-5xl">Kesehatan bukan<br /><em className="font-normal text-secondary">satu ukuran untuk semua.</em></h2></div><p className="max-w-xs text-sm leading-6 text-muted-foreground">Kami menggabungkan keahlian klinis dengan percakapan yang jujur, agar setiap perawatan terasa personal.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{servicesLoading ? <p className="col-span-full py-10 text-center text-sm text-muted-foreground">Memuat layanan terbaru...</p> : services.length === 0 ? <p className="col-span-full py-10 text-center text-sm text-muted-foreground">Belum ada layanan yang tersedia.</p> : services.map((service, i) => { const Icon = serviceIcons[i % serviceIcons.length]; return <article key={service.id} className={`group rounded-[1.75rem] p-7 transition-transform hover:-translate-y-1 ${i === 1 ? 'bg-primary text-primary-foreground' : 'bg-muted'}`}>{i < 2 ? <div className="relative mb-6 overflow-hidden rounded-2xl"><Image src={i === 0 ? '/doctor-interna.png' : '/doctor-obgyn.png'} alt={`Dokter ${service.name}`} width={640} height={420} className="aspect-[3/2] w-full object-cover transition-transform duration-500 group-hover:scale-105" /><span className="absolute bottom-3 left-3 rounded-full bg-card/90 px-3 py-1.5 text-[10px] font-semibold uppercase tracking-[0.12em] text-primary">Dokter spesialis</span></div> : <div className={`mb-20 grid size-12 place-items-center rounded-full ${i === 1 ? 'bg-secondary text-secondary-foreground' : `${service.color || serviceColors[i % serviceColors.length]} text-accent`}`}><Icon className="size-5" /></div>}<h3 className="text-xl font-semibold">{service.name}</h3><p className={`mt-3 text-sm leading-6 ${i === 1 ? 'text-primary-foreground/70' : 'text-muted-foreground'}`}>{service.detail}</p><div className="mt-8 flex items-center justify-between border-t border-current/10 pt-5 text-xs font-semibold"><span>Pelajari lebih lanjut</span><ArrowUpRight className="size-4 transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" /></div></article> })}</div></section>

      <section id="cerita" className="bg-primary px-5 py-20 text-primary-foreground lg:px-10 lg:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div><p className="mb-5 text-xs font-semibold uppercase tracking-[0.2em] text-secondary">Mengapa ruangsehat</p><h2 className="font-serif text-4xl leading-tight sm:text-6xl">Datang sebagai pasien.<br /><em className="font-normal text-secondary">Pulang sebagai diri sendiri.</em></h2></div><div className="grid gap-8 sm:grid-cols-2"><div className="border-l border-primary-foreground/20 pl-5"><p className="font-serif text-3xl text-secondary">01</p><h3 className="mt-4 font-semibold">Didengar sepenuhnya</h3><p className="mt-2 text-sm leading-6 text-primary-foreground/65">Kami menyediakan waktu untuk memahami cerita di balik setiap gejala.</p></div><div className="border-l border-primary-foreground/20 pl-5"><p className="font-serif text-3xl text-secondary">02</p><h3 className="mt-4 font-semibold">Dijelaskan dengan jujur</h3><p className="mt-2 text-sm leading-6 text-primary-foreground/65">Pilihan perawatan selalu dibicarakan dengan bahasa yang mudah dipahami.</p></div><div className="border-l border-primary-foreground/20 pl-5"><p className="font-serif text-3xl text-secondary">03</p><h3 className="mt-4 font-semibold">Ditemani berkelanjutan</h3><p className="mt-2 text-sm leading-6 text-primary-foreground/65">Hubungan kami tidak selesai setelah Anda keluar dari ruang konsultasi.</p></div><div className="border-l border-primary-foreground/20 pl-5"><p className="font-serif text-3xl text-secondary">04</p><h3 className="mt-4 font-semibold">Ruang yang menenangkan</h3><p className="mt-2 text-sm leading-6 text-primary-foreground/65">Lingkungan yang dirancang untuk membuat Anda merasa aman dan nyaman.</p></div></div></div></section>

      <section id="janji" className="mx-auto max-w-7xl px-5 py-24 lg:px-10 lg:py-32"><div className="grid overflow-hidden rounded-[2rem] bg-secondary md:grid-cols-[1fr_0.9fr]"><div className="p-8 sm:p-12 lg:p-16"><p className="mb-5 text-xs font-semibold uppercase tracking-[0.2em] text-secondary-foreground/70">Langkah pertama</p><h2 className="font-serif text-4xl leading-tight text-secondary-foreground sm:text-5xl">Satu percakapan bisa mengubah banyak hal.</h2><p className="mt-5 max-w-md text-sm leading-6 text-secondary-foreground/75">Atur waktu yang nyaman untuk bertemu dokter kami. Tidak perlu menunggu sampai tubuh memberi sinyal lebih keras.</p>{booked ? <div className="mt-8 flex items-center gap-3 rounded-2xl bg-white/30 p-4 text-sm font-semibold text-secondary-foreground"><Check className="size-5" /> Permintaan janji terkirim. Kami akan menghubungi Anda.</div> : <button onClick={() => setBooked(true)} className="mt-8 rounded-full bg-primary px-6 py-3.5 text-sm font-semibold text-primary-foreground transition-transform hover:-translate-y-1">Buat janji temu <ArrowUpRight className="ml-2 inline size-4" /></button>}</div><div className="flex flex-col justify-between bg-card p-8 sm:p-12"><div><p className="text-xs font-semibold uppercase tracking-[0.15em] text-muted-foreground">Ruangsehat Senopati</p><p className="mt-4 text-lg font-semibold text-primary">Jl. Gunawarman No. 42<br />Jakarta Selatan</p></div><div className="mt-10 flex flex-col gap-4 text-sm text-muted-foreground"><span className="flex items-center gap-3"><Clock3 className="size-4 text-accent" /> Senin—Minggu, 07.00—21.00</span><span className="flex items-center gap-3"><Phone className="size-4 text-accent" /> +62 21 555 0123</span><span className="flex items-center gap-3"><CalendarDays className="size-4 text-accent" /> Konsultasi online tersedia</span></div></div></div></section>

      <section id="faq" className="mx-auto grid max-w-7xl gap-12 px-5 pb-24 lg:grid-cols-[0.7fr_1.3fr] lg:px-10"><div><p className="mb-4 text-xs font-semibold uppercase tracking-[0.2em] text-accent">Punya pertanyaan?</p><h2 className="font-serif text-4xl text-primary">Kami siap<br /><em className="font-normal text-secondary">menjawab.</em></h2></div><div>{faqs.map((faq, i) => <button key={faq} onClick={() => setOpenFaq(openFaq === i ? null : i)} className="flex w-full flex-col border-t border-border py-5 text-left"><span className="flex items-center justify-between font-semibold text-primary">{faq}<ChevronDown className={`size-5 transition-transform ${openFaq === i ? 'rotate-180' : ''}`} /></span>{openFaq === i && <span className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground">Tentu. Tim kami akan membantu memberikan informasi yang jelas dan sesuai kebutuhan Anda. Silakan hubungi kami untuk detail selengkapnya.</span>}</button>)}</div></section>

      <footer className="border-t border-border px-5 py-8 lg:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-5 text-xs text-muted-foreground sm:flex-row"><span className="font-semibold tracking-tight text-primary">ruang<span className="text-secondary">sehat</span></span><span>Perawatan yang terasa seperti pulang.</span><span>© 2024 ruangsehat klinik</span></div></footer>
    </main>
  )
}
